/*
 * KubeDB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubedb.client.apis;

import com.kubedb.client.ApiException;
import io.kubernetes.client.openapi.models.V1APIGroupList;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for ApisApi
 */
@Ignore
public class ApisApiTest {

    private final ApisApi api = new ApisApi();

    
    /**
     * 
     *
     * get available API versions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIVersionsTest() throws ApiException {
        V1APIGroupList response = api.getAPIVersions();

        // TODO: test validations
    }
    
}
