/*
 * KubeDB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubedb.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.joda.time.DateTime;

/**
 * V1alpha1RedisStatus
 */

public class V1alpha1RedisStatus {
  @SerializedName("creationTime")
  private DateTime creationTime = null;

  @SerializedName("phase")
  private String phase = null;

  @SerializedName("reason")
  private String reason = null;

  public V1alpha1RedisStatus creationTime(DateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @ApiModelProperty()
  public DateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(DateTime creationTime) {
    this.creationTime = creationTime;
  }

  public V1alpha1RedisStatus phase(String phase) {
    this.phase = phase;
    return this;
  }

   /**
   * Get phase
   * @return phase
  **/
  @ApiModelProperty()
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  public V1alpha1RedisStatus reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty()
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RedisStatus v1alpha1RedisStatus = (V1alpha1RedisStatus) o;
    return Objects.equals(this.creationTime, v1alpha1RedisStatus.creationTime) &&
        Objects.equals(this.phase, v1alpha1RedisStatus.phase) &&
        Objects.equals(this.reason, v1alpha1RedisStatus.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationTime, phase, reason);
  }


  @Override
  public String toString() {

    String sb = "class V1alpha1RedisStatus {\n"
        + "    creationTime: " + toIndentedString(creationTime) + "\n"
        + "    phase: " + toIndentedString(phase) + "\n"
        + "    reason: " + toIndentedString(reason) + "\n"
        + "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

