/*
 * KubeDB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubedb.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * V1alpha1S3Spec
 */

public class V1alpha1S3Spec {
  @SerializedName("bucket")
  private String bucket = null;

  @SerializedName("endpoint")
  private String endpoint = null;

  @SerializedName("prefix")
  private String prefix = null;

  public V1alpha1S3Spec bucket(String bucket) {
    this.bucket = bucket;
    return this;
  }

   /**
   * Get bucket
   * @return bucket
  **/
  @ApiModelProperty(required = true)
  public String getBucket() {
    return bucket;
  }

  public void setBucket(String bucket) {
    this.bucket = bucket;
  }

  public V1alpha1S3Spec endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Get endpoint
   * @return endpoint
  **/
  @ApiModelProperty()
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public V1alpha1S3Spec prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @ApiModelProperty()
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1S3Spec v1alpha1S3Spec = (V1alpha1S3Spec) o;
    return Objects.equals(this.bucket, v1alpha1S3Spec.bucket) &&
        Objects.equals(this.endpoint, v1alpha1S3Spec.endpoint) &&
        Objects.equals(this.prefix, v1alpha1S3Spec.prefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucket, endpoint, prefix);
  }


  @Override
  public String toString() {

    String sb = "class V1alpha1S3Spec {\n"
        + "    bucket: " + toIndentedString(bucket) + "\n"
        + "    endpoint: " + toIndentedString(endpoint) + "\n"
        + "    prefix: " + toIndentedString(prefix) + "\n"
        + "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

