/*
 * KubeDB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubedb.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * V1alpha1InitSpec
 */

public class V1alpha1InitSpec {
  @SerializedName("postgresWAL")
  private V1alpha1PostgresWALSourceSpec postgresWAL = null;

  @SerializedName("scriptSource")
  private V1alpha1ScriptSourceSpec scriptSource = null;

  @SerializedName("snapshotSource")
  private V1alpha1SnapshotSourceSpec snapshotSource = null;

  public V1alpha1InitSpec postgresWAL(V1alpha1PostgresWALSourceSpec postgresWAL) {
    this.postgresWAL = postgresWAL;
    return this;
  }

   /**
   * Get postgresWAL
   * @return postgresWAL
  **/
  @ApiModelProperty()
  public V1alpha1PostgresWALSourceSpec getPostgresWAL() {
    return postgresWAL;
  }

  public void setPostgresWAL(V1alpha1PostgresWALSourceSpec postgresWAL) {
    this.postgresWAL = postgresWAL;
  }

  public V1alpha1InitSpec scriptSource(V1alpha1ScriptSourceSpec scriptSource) {
    this.scriptSource = scriptSource;
    return this;
  }

   /**
   * Get scriptSource
   * @return scriptSource
  **/
  @ApiModelProperty()
  public V1alpha1ScriptSourceSpec getScriptSource() {
    return scriptSource;
  }

  public void setScriptSource(V1alpha1ScriptSourceSpec scriptSource) {
    this.scriptSource = scriptSource;
  }

  public V1alpha1InitSpec snapshotSource(V1alpha1SnapshotSourceSpec snapshotSource) {
    this.snapshotSource = snapshotSource;
    return this;
  }

   /**
   * Get snapshotSource
   * @return snapshotSource
  **/
  @ApiModelProperty()
  public V1alpha1SnapshotSourceSpec getSnapshotSource() {
    return snapshotSource;
  }

  public void setSnapshotSource(V1alpha1SnapshotSourceSpec snapshotSource) {
    this.snapshotSource = snapshotSource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1InitSpec v1alpha1InitSpec = (V1alpha1InitSpec) o;
    return Objects.equals(this.postgresWAL, v1alpha1InitSpec.postgresWAL) &&
        Objects.equals(this.scriptSource, v1alpha1InitSpec.scriptSource) &&
        Objects.equals(this.snapshotSource, v1alpha1InitSpec.snapshotSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postgresWAL, scriptSource, snapshotSource);
  }


  @Override
  public String toString() {

    String sb = "class V1alpha1InitSpec {\n"
        + "    postgresWAL: " + toIndentedString(postgresWAL) + "\n"
        + "    scriptSource: " + toIndentedString(scriptSource) + "\n"
        + "    snapshotSource: " + toIndentedString(snapshotSource) + "\n"
        + "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

